codecov:
  notify:
    require_ci_to_pass: yes
  token: 34f80c4b-f9e2-4df2-9a56-9b60bb252a03

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
